# http://localhost:8308/user/1 访问时，consul-server的集群交替打印
server:
  port: 8308
spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-ribbon-service
service-url:
  consul-user-service: http://consul-user-service
